#
# Copyright (C) 2016  FreeIPA Contributors see COPYING for license
#

from ipaclient.frontend import CommandOverride, Str
from ipalib.plugable import Registry
from ipalib.text import _

register = Registry()

import six

if six.PY3:
    unicode = str

__doc__ = _("""
Temporary command override to display debug data generated by
the server-side plugin
""")

@register(override=True, no_fail=True)
class cert_get_requestdata(CommandOverride):
    has_output_params = (
        Str('debug_output',
            label=_('Debug output'),
        ),
    )
